name: OpenInv
main: com.mcintire.evan.OpenInv
version: 1.0

commands:
  openinv:
    description: Opens the inventory of the player specified.
    usage: /<command> <player>
	
permissions:
  cubeplugin.openinv:
    description: Allows you to open inventories of others
  cubeplugin.openinv.override:
    descrisption: Protects your inventory from being opened